"""Remove unique constraint from installation api_key

Revision ID: 3408675a3b59
Revises: 9764d7b93549
Create Date: 2025-08-12 00:55:44.733229

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3408675a3b59'
down_revision = '9764d7b93549'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_installations_api_key'), table_name='installations')
    op.create_index(op.f('ix_installations_api_key'), 'installations', ['api_key'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_installations_api_key'), table_name='installations')
    op.create_index(op.f('ix_installations_api_key'), 'installations', ['api_key'], unique=True)
    # ### end Alembic commands ###