"""Remove api_key default from installations

Revision ID: 63d1902b79bc
Revises: ac302fef1f56
Create Date: 2025-08-12 00:17:19.905580

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63d1902b79bc'
down_revision = 'ac302fef1f56'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Remove default value from api_key column
    op.alter_column('installations', 'api_key',
                    existing_type=sa.VARCHAR(length=255),
                    server_default=None,
                    existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add back default value for api_key column
    op.alter_column('installations', 'api_key',
                    existing_type=sa.VARCHAR(length=255),
                    server_default=sa.text("concat('inst_', encode(gen_random_bytes(24), 'base64'))"),
                    existing_nullable=False)
    # ### end Alembic commands ###