"""Add admin_api_key to instances

Revision ID: 9764d7b93549
Revises: 63d1902b79bc
Create Date: 2025-08-12 00:23:20.340959

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9764d7b93549'
down_revision = '63d1902b79bc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('instances', sa.Column('admin_api_key', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_instances_admin_api_key'), 'instances', ['admin_api_key'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_instances_admin_api_key'), table_name='instances')
    op.drop_column('instances', 'admin_api_key')
    # ### end Alembic commands ###