"""Initial migration with new monitoring structure

Revision ID: cafef4de6f41
Revises: 
Create Date: 2025-08-11 00:42:25.656796

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cafef4de6f41'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clients',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('timezone', sa.String(length=50), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clients_id'), 'clients', ['id'], unique=False)
    op.create_index(op.f('ix_clients_is_active'), 'clients', ['is_active'], unique=False)
    op.create_index(op.f('ix_clients_name'), 'clients', ['name'], unique=True)
    op.create_table('modules',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('relative_path', sa.String(length=500), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('version', sa.String(length=50), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_modules_id'), 'modules', ['id'], unique=False)
    op.create_index(op.f('ix_modules_name'), 'modules', ['name'], unique=True)
    op.create_table('endpoints',
    sa.Column('module_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('relative_path', sa.String(length=500), nullable=False),
    sa.Column('method', sa.String(length=10), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.Column('expected_response_time_ms', sa.Integer(), nullable=False),
    sa.Column('timeout_ms', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['module_id'], ['modules.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_endpoints_id'), 'endpoints', ['id'], unique=False)
    op.create_index(op.f('ix_endpoints_module_id'), 'endpoints', ['module_id'], unique=False)
    op.create_table('instances',
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('host', sa.String(length=255), nullable=False),
    sa.Column('environment', sa.String(length=50), nullable=True),
    sa.Column('version', sa.String(length=50), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_instances_client_id'), 'instances', ['client_id'], unique=False)
    op.create_index(op.f('ix_instances_id'), 'instances', ['id'], unique=False)
    op.create_index(op.f('ix_instances_is_active'), 'instances', ['is_active'], unique=False)
    op.create_table('installations',
    sa.Column('module_id', sa.UUID(), nullable=False),
    sa.Column('instance_id', sa.UUID(), nullable=False),
    sa.Column('config', sa.JSON(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['instance_id'], ['instances.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['module_id'], ['modules.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('module_id', 'instance_id', name='_module_instance_uc')
    )
    op.create_index(op.f('ix_installations_id'), 'installations', ['id'], unique=False)
    op.create_index(op.f('ix_installations_instance_id'), 'installations', ['instance_id'], unique=False)
    op.create_index(op.f('ix_installations_is_active'), 'installations', ['is_active'], unique=False)
    op.create_index(op.f('ix_installations_module_id'), 'installations', ['module_id'], unique=False)
    op.create_table('monitoring_logs',
    sa.Column('installation_id', sa.UUID(), nullable=False),
    sa.Column('endpoint_id', sa.UUID(), nullable=False),
    sa.Column('response_time_ms', sa.Integer(), nullable=True),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('response_body', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('alert_level', sa.String(length=20), nullable=True),
    sa.Column('alert_triggered', sa.Boolean(), nullable=False),
    sa.Column('extra_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['endpoint_id'], ['endpoints.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['installation_id'], ['installations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_monitoring_logs_alert_level'), 'monitoring_logs', ['alert_level'], unique=False)
    op.create_index(op.f('ix_monitoring_logs_created_at'), 'monitoring_logs', ['created_at'], unique=False)
    op.create_index('ix_monitoring_logs_created_desc', 'monitoring_logs', [sa.literal_column('created_at DESC')], unique=False)
    op.create_index(op.f('ix_monitoring_logs_id'), 'monitoring_logs', ['id'], unique=False)
    op.create_index('ix_monitoring_logs_installation_endpoint_created', 'monitoring_logs', ['installation_id', 'endpoint_id', 'created_at'], unique=False)
    op.create_table('thresholds',
    sa.Column('installation_id', sa.UUID(), nullable=False),
    sa.Column('endpoint_id', sa.UUID(), nullable=False),
    sa.Column('metric_type', sa.String(length=50), nullable=False),
    sa.Column('warning_min', sa.Numeric(), nullable=True),
    sa.Column('warning_max', sa.Numeric(), nullable=True),
    sa.Column('error_min', sa.Numeric(), nullable=True),
    sa.Column('error_max', sa.Numeric(), nullable=True),
    sa.Column('expected_values', sa.JSON(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['endpoint_id'], ['endpoints.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['installation_id'], ['installations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('installation_id', 'endpoint_id', 'metric_type', name='_installation_endpoint_metric_uc')
    )
    op.create_index(op.f('ix_thresholds_endpoint_id'), 'thresholds', ['endpoint_id'], unique=False)
    op.create_index(op.f('ix_thresholds_id'), 'thresholds', ['id'], unique=False)
    op.create_index(op.f('ix_thresholds_installation_id'), 'thresholds', ['installation_id'], unique=False)
    op.create_index(op.f('ix_thresholds_is_active'), 'thresholds', ['is_active'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_thresholds_is_active'), table_name='thresholds')
    op.drop_index(op.f('ix_thresholds_installation_id'), table_name='thresholds')
    op.drop_index(op.f('ix_thresholds_id'), table_name='thresholds')
    op.drop_index(op.f('ix_thresholds_endpoint_id'), table_name='thresholds')
    op.drop_table('thresholds')
    op.drop_index('ix_monitoring_logs_installation_endpoint_created', table_name='monitoring_logs')
    op.drop_index(op.f('ix_monitoring_logs_id'), table_name='monitoring_logs')
    op.drop_index('ix_monitoring_logs_created_desc', table_name='monitoring_logs')
    op.drop_index(op.f('ix_monitoring_logs_created_at'), table_name='monitoring_logs')
    op.drop_index(op.f('ix_monitoring_logs_alert_level'), table_name='monitoring_logs')
    op.drop_table('monitoring_logs')
    op.drop_index(op.f('ix_installations_module_id'), table_name='installations')
    op.drop_index(op.f('ix_installations_is_active'), table_name='installations')
    op.drop_index(op.f('ix_installations_instance_id'), table_name='installations')
    op.drop_index(op.f('ix_installations_id'), table_name='installations')
    op.drop_table('installations')
    op.drop_index(op.f('ix_instances_is_active'), table_name='instances')
    op.drop_index(op.f('ix_instances_id'), table_name='instances')
    op.drop_index(op.f('ix_instances_client_id'), table_name='instances')
    op.drop_table('instances')
    op.drop_index(op.f('ix_endpoints_module_id'), table_name='endpoints')
    op.drop_index(op.f('ix_endpoints_id'), table_name='endpoints')
    op.drop_table('endpoints')
    op.drop_index(op.f('ix_modules_name'), table_name='modules')
    op.drop_index(op.f('ix_modules_id'), table_name='modules')
    op.drop_table('modules')
    op.drop_index(op.f('ix_clients_name'), table_name='clients')
    op.drop_index(op.f('ix_clients_is_active'), table_name='clients')
    op.drop_index(op.f('ix_clients_id'), table_name='clients')
    op.drop_table('clients')
    # ### end Alembic commands ###